package repogovernance

import (
	"bytes"
	"fmt"
	"strings"
)

func renderDocument(doc Document) []byte {
	var out bytes.Buffer
	fmt.Fprintf(&out, "# %s\n\n<!-- generated by shortsctl; do not edit by hand -->\n\n%s\n", doc.Title, doc.Summary)
	for _, section := range doc.Sections {
		fmt.Fprintf(&out, "\n## %s\n", section.Heading)
		for _, paragraph := range section.Paragraphs {
			fmt.Fprintf(&out, "\n%s\n", paragraph)
		}
		if len(section.Bullets) > 0 {
			out.WriteByte('\n')
			for _, item := range section.Bullets {
				fmt.Fprintf(&out, "- %s\n", item)
			}
		}
		if section.Code != "" {
			fmt.Fprintf(&out, "\n```%s\n%s\n```\n", section.CodeLanguage, strings.TrimSuffix(section.Code, "\n"))
		}
	}
	return out.Bytes()
}
