(in-package #:myhome-jarvis.ssot)

(defun validate-finance-consent-policy (policy)
  (require-string-equal (getf policy :context)
                        "HouseholdFinanceConsentLedger"
                        "Finance consent policy context mismatch")
  (require-private-jsonl (getf policy :private_consent_ledger)
                         "Finance consent ledger must stay private JSONL")
  (require-true (and (getf policy :append_only)
                     (getf policy :public_status_redacted))
                "Finance consent ledger must be append-only and redacted")
  (require-true (and (getf policy :read_only)
                     (getf policy :review_only)
                     (getf policy :fixture_only_until_consent))
                "Finance must stay read-only, review-only, and fixture-first")
  (require-finance-no-write-actions policy)
  (require-true (and (getf policy :real_connector_requires_active_consent)
                     (getf policy :spouse_scope_requires_active_consent)
                     (getf policy :household_scope_requires_active_consent))
                "Finance connector and shared scopes require active consent")
  (validate-finance-consent-lists policy)
  (require-command policy "mhj finance-consent status"))

(defun require-finance-no-write-actions (policy)
  (dolist (key '(:external_writes_allowed :transfer_actions_allowed
                 :payment_actions_allowed :trade_actions_allowed
                 :card_actions_allowed))
    (require-false (getf policy key)
                   "Finance consent policy must not allow external write actions")))

(defun validate-finance-consent-lists (policy)
  (require-members '("finance_connector" "spouse_scope" "household_scope")
                   (policy-list policy :consent_kinds)
                   "Finance consent kind missing: ~A")
  (require-members '("requested" "granted" "revoked" "expired" "denied")
                   (policy-list policy :consent_statuses)
                   "Finance consent status missing: ~A")
  (require-members '("requested" "approved" "rejected")
                   (policy-list policy :review_statuses)
                   "Finance consent review status missing: ~A")
  (require-members '("at" "consent_kind" "subject_scope" "status"
                     "review_status" "authority_profile" "evidence_refs")
                   (policy-list policy :required_fields)
                   "Finance consent required field missing: ~A"))
