(in-package #:myhome-jarvis.ssot)

(defun validate-code-shape-policy (policy)
  (let ((legacy (policy-list policy :legacy_debt_files))
        (summary (policy-list policy :public_summary_fields)))
    (require-string-equal (getf policy :context) "AgentCluster"
                          "Code shape policy must belong to AgentCluster")
    (require-string-equal (getf policy :generated_artifact)
                          "generated/code_shape.generated.json"
                          "Code shape generated artifact path is invalid")
    (require-true (= (getf policy :max_file_lines) 75)
                  "Code shape max file lines must stay 75")
    (require-true (getf policy :public_status_redacted)
                  "Code shape public status must stay redacted")
    (validate-code-shape-globs policy)
    (dolist (entry legacy)
      (validate-code-shape-legacy-entry entry))
    (require-members '("budget_regression_count" "legacy_debt_count" "ok")
                     summary "Code shape public summary missing field: ~A")
    (require-command policy "mhj code-shape status")))

(defun validate-code-shape-globs (policy)
  (let ((roots (policy-list policy :source_roots))
        (extensions (policy-list policy :extensions)))
    (require-true (and (> (length roots) 0) (> (length extensions) 0))
                  "Code shape roots and extensions are required")
    (dolist (extension extensions)
      (require-true (and (stringp extension)
                         (> (length extension) 1)
                         (char= (aref extension 0) #\.))
                    "Code shape extension is invalid: ~A" extension))))

(defun validate-code-shape-legacy-entry (entry)
  (let ((path (getf entry :path))
        (max-lines (getf entry :max_lines)))
    (require-true (and (stringp path) (> (length path) 0)
                       (not (char= (aref path 0) #\/))
                       (not (search ".." path))
                       (integerp max-lines)
                       (> max-lines 75))
                  "Code shape legacy debt entry is invalid: ~A" path)))

(defun validate-learning-policy (policy)
  (require-private-path (getf policy :private_ledger)
                        "Learning ledger must stay under data/private")
  (require-true (getf policy :append_only)
                "Learning ledger must be append-only")
  (require-true (getf policy :private_journal_required)
                "Learning ledger must require a private journal")
  (require-true (getf policy :public_status_redacted)
                "Learning public status must stay redacted")
  (require-false (getf policy :raw_observation_public_allowed)
                 "Learning status must not expose raw observations")
  (require-members '("kind" "source" "summary" "evidence_refs" "owner"
                     "next_action")
                   (policy-list policy :required_fields)
                   "Learning policy missing required field: ~A")
  (require-members '("loop_gap" "evidence_debt")
                   (policy-list policy :allowed_kinds)
                   "Learning policy missing kind: ~A")
  (require-members '("observed" "evidence_recorded" "owner_assigned"
                     "verified" "knowledge_updated")
                   (policy-list policy :lifecycle)
                   "Learning lifecycle missing stage: ~A")
  (require-members '("open" "closed") (policy-list policy :allowed_statuses)
                   "Learning allowed status missing: ~A")
  (require-member "data/private/" (policy-list policy :allowed_evidence_prefixes)
                  "Learning evidence refs must allow private evidence paths")
  (require-command policy "mhj learning status")
  (require-command policy "mhj learning record <json-payload>"))
