(in-package #:myhome-jarvis.ssot)

(defun wf-unit (stream unit)
  (wf stream "  ~A:" (getf unit :id))
  (wf stream "    name: ~A" (getf unit :name))
  (wf stream "    runs-on: ubuntu-latest")
  (wf stream "    timeout-minutes: ~A" (getf unit :timeout))
  (wf stream "")
  (wf stream "    steps:")
  (wf-checkout stream unit)
  (wf-restore-cache stream unit)
  (wf-report-cache stream unit)
  (wf-setup stream unit)
  (wf-command-step stream unit)
  (wf-failure-artifact stream unit)
  (wf-prepare-cache stream unit)
  (wf-save-cache stream unit)
  (wf stream ""))

(defun wf-restore-cache (stream unit)
  (when (getf unit :cache)
    (wf stream "      - name: Restore ~A unit cache" (getf unit :name))
    (wf stream "        id: unit-cache")
    (wf stream "        uses: ~A" (github-action-ref "cache-restore"))
    (wf stream "        with:")
    (wf stream "          path: .github/unit-cache/~A" (getf unit :cache))
    (wf stream "          key: ~A-${{ runner.os }}-${{ env.UNIT_CACHE_VERSION }}-~A"
        (getf unit :cache) (wf-hash-files unit))))

(defun wf-report-cache (stream unit)
  (when (getf unit :cache)
    (wf stream "      - name: Report ~A cache hit" (getf unit :name))
    (wf stream "        if: steps.unit-cache.outputs.cache-hit == 'true'")
    (wf stream "        run: echo \"~A unchanged for this unit hash.\""
        (getf unit :name))))

(defun wf-prepare-cache (stream unit)
  (when (getf unit :cache)
    (wf stream "      - name: Prepare ~A unit cache marker" (getf unit :name))
    (wf-if stream (wf-cache-miss-if unit))
    (wf-run-block stream
                  (list (format nil "mkdir -p .github/unit-cache/~A" (getf unit :cache))
                        (format nil "printf '%s\\n' '${{ steps.unit-cache.outputs.cache-primary-key }}' > .github/unit-cache/~A/key" (getf unit :cache)))
                  "        ")))

(defun wf-save-cache (stream unit)
  (when (getf unit :cache)
    (wf stream "      - name: Save ~A unit cache" (getf unit :name))
    (wf stream "        if: steps.unit-cache.outputs.cache-hit != 'true' && github.event_name == 'push' && github.repository == 'kimsemi-home/myhome-jarvis'")
    (wf stream "        uses: ~A" (github-action-ref "cache-save"))
    (wf stream "        continue-on-error: true")
    (wf stream "        with:")
    (wf stream "          path: .github/unit-cache/~A" (getf unit :cache))
  (wf stream "          key: ${{ steps.unit-cache.outputs.cache-primary-key }}")))

(defun wf-failure-artifact (stream unit)
  (when (getf unit :failure_artifact)
    (wf stream "      - name: Upload ~A diagnostics" (getf unit :name))
    (wf stream "        if: failure() && ~A" (wf-cache-miss-if unit))
    (wf stream "        uses: ~A" (github-action-ref "upload-artifact"))
    (wf stream "        with:")
    (wf stream "          name: ~A-diagnostics-${{ github.run_id }}" (getf unit :id))
    (wf stream "          path: ~A" (getf unit :failure_artifact))
    (wf stream "          if-no-files-found: ignore")
    (wf stream "          retention-days: 3")))
