(in-package #:myhome-jarvis.ssot)

(defun write-quality-workflows (root)
  (dolist (path (quality-workflow-paths root))
    (ensure-directories-exist path)
    (with-open-file (stream path
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
      (emit-quality-workflow stream))))

(defun quality-workflow-paths (root)
  (list (merge-pathnames "generated/github_quality_workflow.generated.yml" root)
        (merge-pathnames ".github/workflows/quality.yml" root)))

(defun emit-quality-workflow (stream)
  (wf stream "# Generated from lisp/ssot/verification-graph.lisp.")
  (wf stream "name: quality")
  (wf stream "")
  (wf stream "on:")
  (wf stream "  push:")
  (wf stream "    branches: [\"**\"]")
  (wf stream "  pull_request:")
  (wf stream "")
  (wf stream "concurrency:")
  (wf stream "  group: ${{ github.workflow }}-${{ github.ref }}")
  (wf stream "  cancel-in-progress: true")
  (wf stream "")
  (wf stream "permissions:")
  (wf stream "  contents: read")
  (wf stream "")
  (wf stream "env:")
  (wf stream "  GO_VERSION: \"~A\"" (getf *project* :go_version))
  (wf stream "  FLUTTER_VERSION: \"3.44.2\"")
  (wf stream "  RUST_TOOLCHAIN: \"1.96.0\"")
  (wf stream "  LISP: \"sbcl-bin\"")
  (wf stream "  UNIT_CACHE_VERSION: \"v1\"")
  (wf stream "")
  (wf stream "jobs:")
  (dolist (unit (policy-list *verification-graph* :units))
    (wf-unit stream unit))
  (wf-summary-job stream (mapcar (lambda (unit) (getf unit :id))
                                 (policy-list *verification-graph* :units))))

(defun wf-summary-job (stream unit-ids)
  (wf stream "  quality:")
  (wf stream "    name: Quality summary")
  (wf stream "    runs-on: ubuntu-latest")
  (wf stream "    needs: [~A]" (wf-join unit-ids))
  (wf stream "    if: always()")
  (wf stream "    timeout-minutes: 5")
  (wf stream "")
  (wf stream "    steps:")
  (wf stream "      - name: Check unit results")
  (wf-run-block stream (wf-summary-lines unit-ids) "        "))

(defun wf-summary-lines (unit-ids)
  (append
   (mapcar (lambda (id) (format nil "echo \"~A=${{ needs.~A.result }}\"" id id))
           unit-ids)
   (mapcar (lambda (id) (format nil "test \"${{ needs.~A.result }}\" = \"success\"" id))
           unit-ids)))
