(in-package #:myhome-jarvis.ssot)

(defun validate-linear-policy (policy)
  (require-true (getf policy :pull_active_only)
                "Linear pull must stay scoped to active issues by default")
  (require-true (getf policy :team_scope_private)
                "Linear team scope must stay private")
  (require-string-equal (getf policy :project_issue_title_prefix)
                        "[myhome-jarvis]"
                        "Linear project title prefix must identify work")
  (require-true (getf policy :next_prefers_project_issues)
                "Linear next must prefer project issues")
  (require-true (getf policy :next_requires_project_issue)
                "Linear next must not select unrelated active issues")
  (require-true (getf policy :backlog_seed_current_project_only)
                "Linear backlog seeds must represent current project work")
  (require-true (getf policy :backlog_seed_dedupes_by_title)
                "Linear backlog seeding must dedupe existing issue titles")
  (require-true (getf policy :backlog_seed_queries_existing_titles)
                "Linear backlog seeding must query existing issue titles")
  (require-string-equal (getf policy :offline_replay_evidence)
                        "data/private/linear-offline-replay.jsonl"
                        "Linear offline replay evidence must stay private")
  (require-positive-integer (getf policy :offline_replay_rate_limit_floor)
                            "Linear offline replay rate limit must be positive")
  (require-command policy "mhj linear replay-offline")
  (require-members '("linear_comment" "linear_transition")
                   (policy-list policy :offline_replay_safe_action_kinds)
                   "Linear offline replay safe action kind missing: ~A"))

(defun validate-planner-policy (policy)
  (let ((tasks (policy-list policy :task_graph)))
    (require-true (> (length tasks) 0)
                  "Planner policy must include a task graph")
    (require-member "linear_sync" (mapcar (lambda (task) (getf task :id)) tasks)
                    "Planner task graph must include Linear sync boundary"))
  (require-true (getf policy :knowledge_index_required_before_planning)
                "Planner must require KnowledgeIndex before planning")
  (validate-planner-gate (getf policy :external_write_gate)))

(defun validate-planner-gate (gate)
  (require-true (and (getf gate :standing_boundary)
                     (getf gate :approval_required)
                     (getf gate :mutation_success_required)
                     (string= (getf gate :boundary_task_id) "linear_sync")
                     (string= (getf gate :evidence_path)
                              "data/private/linear-write-evidence.jsonl"))
                "Planner external-write gate policy must stay explicit"))
