(in-package #:myhome-jarvis.ssot)

(defun validate-agent-cluster-policy (policy)
  (require-true (getf policy :public_safe)
                "Agent cluster policy must be public-safe")
  (require-false (getf policy :raw_transcript_storage_allowed)
                 "Agent cluster policy must not store raw transcripts")
  (require-false (getf policy :private_data_in_evidence_allowed)
                 "Agent cluster policy must not allow private data publicly")
  (require-false (getf policy :external_agent_execution_allowed)
                 "Agent cluster policy must not enable external execution")
  (require-false (getf policy :self_approval_allowed)
                 "Agent cluster policy must not allow self-approval")
  (require-false (getf policy :confidence_self_report_allowed)
                 "Agent cluster confidence must be assessed externally")
  (require-true (getf policy :authority_gate_required)
                "Agent cluster policy must require an authority gate")
  (validate-agent-cluster-flow policy)
  (validate-agent-cluster-roles policy)
  (require-command policy "mhj agent-cluster status"))

(defun validate-agent-cluster-flow (policy)
  (let ((flow (policy-list policy :evidence_flow))
        (lifecycle (policy-list policy :incident_lifecycle)))
    (require-members '("observation" "evidence" "interpretation" "rulebook"
                       "code" "verification_evidence" "knowledge_update")
                     flow "Agent cluster evidence flow missing stage: ~A")
    (require-true (ordered-agent-flow-p flow)
                  "Agent cluster evidence flow order is invalid")
    (require-members '("observed" "evidence_recorded" "classified"
                       "owner_assigned" "verified" "knowledge_updated")
                     lifecycle "Agent cluster lifecycle missing stage: ~A")))

(defun ordered-agent-flow-p (flow)
  (let ((observation (position "observation" flow :test #'string=))
        (evidence (position "evidence" flow :test #'string=))
        (code (position "code" flow :test #'string=))
        (verification (position "verification_evidence" flow :test #'string=))
        (knowledge (position "knowledge_update" flow :test #'string=)))
    (and observation evidence code verification knowledge
         (< observation evidence code verification knowledge))))

(defun validate-agent-cluster-roles (policy)
  (let ((roles (policy-list policy :agent_roles))
        (sidecars (policy-list policy :sidecars)))
    (require-true (>= (length roles) 4)
                  "Agent cluster policy must declare separated roles")
    (dolist (role roles)
      (let ((key (getf role :key)))
        (require-string-value key "Agent cluster role key is required")
        (require-true (> (length (getf role :must_produce)) 0)
                      "Agent cluster role ~A must declare produced evidence" key)
        (require-true (> (length (getf role :must_not)) 0)
                      "Agent cluster role ~A must declare forbidden authority" key)))
    (require-true (>= (length sidecars) 4)
                  "Agent cluster policy must declare verification sidecars")))
