(in-package #:myhome-jarvis.ssot)

(defun validate-ssot ()
  (validate-command-catalog)
  (validate-foundation-policies)
  (validate-security-policy-basics)
  (validate-connector-policy *connector-policy*)
  (validate-agent-cluster-policy *agent-cluster-policy*)
  (validate-code-shape-policy *code-shape-policy*)
  (validate-learning-policy *learning-policy*)
  (validate-evidence-graph-policy *evidence-graph-policy*)
  (validate-confidence-policy *confidence-policy*)
  (validate-translation-policy *translation-policy*)
  (validate-control-plane-policy *control-plane-policy*)
  (validate-incident-policy *incident-policy*)
  (validate-evidence-quality-policy *evidence-quality-policy*)
  (validate-review-policy *review-policy*)
  (validate-assistant-vision-policy *assistant-vision-policy*)
  (validate-codex-cost-policy *codex-cost-policy*)
  (validate-authority-policy *authority-policy*)
  (validate-pdca-policy *pdca-policy*)
  (validate-linear-policy *linear-policy*)
  (validate-ddd-registry)
  (validate-planner-policy *planner-policy*)
  (validate-verification-graph *verification-graph*)
  t)

(defun write-generated-artifacts (root)
  (validate-ssot)
  (write-all-generated-artifacts root)
  t)
