(in-package #:myhome-jarvis.ssot)

(defun validate-monetization-policy (policy)
  (require-string-equal (getf policy :context)
                        "MonetizationExperimentLedger"
                        "Monetization policy context mismatch")
  (require-private-jsonl (getf policy :private_experiment_ledger)
                         "Monetization ledger must stay private JSONL")
  (require-true (and (getf policy :append_only)
                     (getf policy :public_status_redacted))
                "Monetization records must be append-only and redacted")
  (require-false (getf policy :raw_revenue_public_allowed)
                 "Monetization public status must not expose raw revenue")
  (require-true (and (getf policy :decision_evidence_required)
                     (getf policy :cost_estimate_required))
                "Monetization decisions require evidence and cost")
  (validate-monetization-lists policy)
  (require-command policy "mhj monetization status"))

(defun validate-monetization-lists (policy)
  (require-members '("backlog" "review_required" "running" "closed")
                   (policy-list policy :experiment_states)
                   "Monetization state missing: ~A")
  (require-members '("hypothesis_created" "scale_requested" "close_experiment")
                   (policy-list policy :decision_kinds)
                   "Monetization decision kind missing: ~A")
  (require-members '("requested" "approved" "rejected" "not_required")
                   (policy-list policy :review_statuses)
                   "Monetization review status missing: ~A")
  (require-members '("unknown" "low" "medium" "high")
                   (policy-list policy :expected_value_bands)
                   "Monetization expected value band missing: ~A")
  (require-members '("at" "experiment_id" "hypothesis_key" "state"
                     "decision_kind" "review_status" "expected_value_band"
                     "cost_estimate_units" "cost_unit_kind" "evidence_refs")
                   (policy-list policy :required_fields)
                   "Monetization required field missing: ~A"))
