(in-package #:myhome-jarvis.ssot)

(defun validate-ssot ()
  (let ((command-names (mapcar (lambda (command) (getf command :name)) *commands*)))
    (dolist (required '("open_youtube"
                        "open_youtube_search"
                        "open_netflix"
                        "open_disney_plus"
                        "open_tving"
                        "open_wavve"
                        "open_coupang_play"
                        "open_ott"
                        "open_url"
                        "volume_set"
                        "volume_up"
                        "volume_down"
                        "display_sleep"
                        "movie_mode"
                        "sleep_mode"))
      (unless (member required command-names :test #'string=)
        (error "Missing required command: ~A" required)))
    (when (find "Python" *allowed-languages* :test #'string=)
      (error "Python must not be an allowed language"))
    (unless (find "raw" (getf *storage-policy* :lake_layers) :test #'string=)
      (error "Storage policy must include raw layer"))
    (unless (find "spouse" (coerce (getf *household-policy* :scopes) 'list) :test #'string=)
      (error "Household policy must include spouse scope"))
    (unless (find "subscription_review" (coerce (getf *recommendation-policy* :kinds) 'list) :test #'string=)
      (error "Recommendation policy must include subscription review"))
    (unless (getf *scheduler-policy* :crash_recovery)
      (error "Scheduler policy must require crash recovery"))
    (unless (getf *security-policy* :lan_requires_bearer_token)
      (error "LAN daemon access must require a bearer token"))
    (unless (getf *security-policy* :current_content_scan)
      (error "Current-tree content scanning must stay enabled"))
    (unless (getf *security-policy* :current_content_scan_skips_private_paths)
      (error "Current-tree content scanning must skip private paths"))
    (when (getf *security-policy* :report_matched_secret_contents)
      (error "Security reports must not expose matched secret contents"))
    (unless (getf *connector-policy* :fixture_only)
      (error "Connector readiness must remain fixture-only in public SSOT"))
    (when (getf *connector-policy* :real_credentials_allowed)
      (error "Connector readiness must not allow real credentials"))
    (when (getf *connector-policy* :external_api_calls_allowed)
      (error "Connector readiness must not allow external API calls"))
    (unless (> (length (getf *connector-policy* :connectors)) 0)
      (error "Connector readiness must declare planned connectors"))
    (dolist (connector (coerce (getf *connector-policy* :connectors) 'list))
      (let ((key (getf connector :key))
            (fixture-mode (getf connector :fixture_mode))
            (allowed (coerce (getf connector :allowed_operations) 'list)))
        (when (or (null key) (string= key ""))
          (error "Connector key is required"))
        (unless fixture-mode
          (error "Connector ~A must stay in fixture mode" key))
        (when (find "external_api_call" allowed :test #'string=)
          (error "Connector ~A must not allow external API calls" key))
        (when (find "credential_request" allowed :test #'string=)
          (error "Connector ~A must not allow credential requests" key))))
    (unless (getf *agent-cluster-policy* :public_safe)
      (error "Agent cluster policy must be public-safe"))
    (when (getf *agent-cluster-policy* :raw_transcript_storage_allowed)
      (error "Agent cluster policy must not store raw transcripts"))
    (when (getf *agent-cluster-policy* :private_data_in_evidence_allowed)
      (error "Agent cluster policy must not allow private data in public evidence"))
    (when (getf *agent-cluster-policy* :external_agent_execution_allowed)
      (error "Agent cluster policy must not enable external agent execution"))
    (when (getf *agent-cluster-policy* :self_approval_allowed)
      (error "Agent cluster policy must not allow self-approval"))
    (when (getf *agent-cluster-policy* :confidence_self_report_allowed)
      (error "Agent cluster confidence must be assessed externally"))
    (unless (getf *agent-cluster-policy* :authority_gate_required)
      (error "Agent cluster policy must require an authority gate"))
    (validate-agent-cluster-policy *agent-cluster-policy*)
    (validate-learning-policy *learning-policy*)
    (validate-evidence-graph-policy *evidence-graph-policy*)
    (validate-confidence-policy *confidence-policy*)
    (validate-translation-policy *translation-policy*)
    (validate-control-plane-policy *control-plane-policy*)
    (unless (getf *linear-policy* :pull_active_only)
      (error "Linear pull must stay scoped to active issues by default"))
    (unless (getf *linear-policy* :team_scope_private)
      (error "Linear team scope must stay private"))
    (unless (string= (getf *linear-policy* :project_issue_title_prefix)
                     "[myhome-jarvis]")
      (error "Linear project issue title prefix must identify myhome-jarvis work"))
    (unless (getf *linear-policy* :next_prefers_project_issues)
      (error "Linear next must prefer project issues"))
    (unless (getf *linear-policy* :next_requires_project_issue)
      (error "Linear next must not select unrelated active issues"))
    (unless (getf *linear-policy* :backlog_seed_current_project_only)
      (error "Linear backlog seeds must represent current project work"))
    (unless (getf *linear-policy* :backlog_seed_dedupes_by_title)
      (error "Linear backlog seeding must dedupe existing issue titles"))
    (unless (getf *linear-policy* :backlog_seed_queries_existing_titles)
      (error "Linear backlog seeding must query existing issue titles"))
    (unless (string= (getf *linear-policy* :offline_replay_evidence)
                     "data/private/linear-offline-replay.jsonl")
      (error "Linear offline replay evidence must stay private"))
    (unless (and (integerp (getf *linear-policy* :offline_replay_rate_limit_floor))
                 (> (getf *linear-policy* :offline_replay_rate_limit_floor) 0))
      (error "Linear offline replay rate limit floor must be positive"))
    (unless (find "mhj linear replay-offline"
                  (coerce (getf *linear-policy* :commands) 'list)
                  :test #'string=)
      (error "Linear replay-offline command must stay in SSOT"))
    (dolist (kind '("linear_comment" "linear_transition"))
      (unless (find kind
                    (coerce (getf *linear-policy* :offline_replay_safe_action_kinds) 'list)
                    :test #'string=)
        (error "Linear offline replay safe action kind missing: ~A" kind)))
    (validate-ddd-registry)
    (unless (> (length (getf *planner-policy* :task_graph)) 0)
      (error "Planner policy must include a task graph"))
    (unless (find "linear_sync"
                  (coerce (map 'vector (lambda (task) (getf task :id))
                               (getf *planner-policy* :task_graph))
                          'list)
                  :test #'string=)
      (error "Planner task graph must include Linear sync boundary"))
    (unless (getf *planner-policy* :knowledge_index_required_before_planning)
      (error "Planner must require KnowledgeIndex lookup before planning"))
    (let ((gate (getf *planner-policy* :external_write_gate)))
      (unless (and (getf gate :standing_boundary)
                   (getf gate :approval_required)
                   (getf gate :mutation_success_required)
                   (string= (getf gate :boundary_task_id) "linear_sync")
                   (string= (getf gate :evidence_path)
                            "data/private/linear-write-evidence.jsonl"))
        (error "Planner external-write gate policy must stay explicit and private")))
    t))

(defun validate-agent-cluster-policy (policy)
  (let ((flow (coerce (getf policy :evidence_flow) 'list))
        (lifecycle (coerce (getf policy :incident_lifecycle) 'list))
        (roles (coerce (getf policy :agent_roles) 'list))
        (sidecars (coerce (getf policy :sidecars) 'list)))
    (dolist (stage '("observation"
                     "evidence"
                     "interpretation"
                     "rulebook"
                     "code"
                     "verification_evidence"
                     "knowledge_update"))
      (unless (find stage flow :test #'string=)
        (error "Agent cluster evidence flow missing stage: ~A" stage)))
    (let ((observation (position "observation" flow :test #'string=))
          (evidence (position "evidence" flow :test #'string=))
          (code (position "code" flow :test #'string=))
          (verification (position "verification_evidence" flow :test #'string=))
          (knowledge (position "knowledge_update" flow :test #'string=)))
      (unless (and observation evidence code verification knowledge
                   (< observation evidence)
                   (< evidence code)
                   (< code verification)
                   (< verification knowledge))
        (error "Agent cluster evidence flow must be observation -> evidence -> code -> verification -> knowledge")))
    (dolist (stage '("observed"
                     "evidence_recorded"
                     "classified"
                     "owner_assigned"
                     "verified"
                     "knowledge_updated"))
      (unless (find stage lifecycle :test #'string=)
        (error "Agent cluster lifecycle missing stage: ~A" stage)))
    (unless (>= (length roles) 4)
      (error "Agent cluster policy must declare separated roles"))
    (dolist (role roles)
      (let ((key (getf role :key))
            (must-produce (coerce (getf role :must_produce) 'list))
            (must-not (coerce (getf role :must_not) 'list)))
        (when (or (null key) (string= key ""))
          (error "Agent cluster role key is required"))
        (unless (> (length must-produce) 0)
          (error "Agent cluster role ~A must declare produced evidence" key))
        (unless (> (length must-not) 0)
          (error "Agent cluster role ~A must declare forbidden authority" key))))
    (unless (>= (length sidecars) 4)
      (error "Agent cluster policy must declare verification sidecars"))
    (unless (find "mhj agent-cluster status"
                  (coerce (getf policy :commands) 'list)
                  :test #'string=)
      (error "Agent cluster status command must stay in SSOT"))
    t))

(defun validate-learning-policy (policy)
  (let ((ledger (getf policy :private_ledger))
        (required (coerce (getf policy :required_fields) 'list))
        (kinds (coerce (getf policy :allowed_kinds) 'list))
        (lifecycle (coerce (getf policy :lifecycle) 'list))
        (statuses (coerce (getf policy :allowed_statuses) 'list))
        (prefixes (coerce (getf policy :allowed_evidence_prefixes) 'list)))
    (unless (and (stringp ledger)
                 (>= (length ledger) 13)
                 (string= "data/private/" (subseq ledger 0 13)))
      (error "Learning ledger must stay under data/private"))
    (unless (getf policy :append_only)
      (error "Learning ledger must be append-only"))
    (unless (getf policy :private_journal_required)
      (error "Learning ledger must require a private journal"))
    (unless (getf policy :public_status_redacted)
      (error "Learning public status must stay redacted"))
    (when (getf policy :raw_observation_public_allowed)
      (error "Learning status must not expose raw observations"))
    (dolist (field '("kind" "source" "summary" "evidence_refs" "owner" "next_action"))
      (unless (find field required :test #'string=)
        (error "Learning policy missing required field: ~A" field)))
    (unless (find "loop_gap" kinds :test #'string=)
      (error "Learning policy must track loop gaps"))
    (unless (find "evidence_debt" kinds :test #'string=)
      (error "Learning policy must track evidence debt"))
    (dolist (stage '("observed" "evidence_recorded" "owner_assigned" "verified" "knowledge_updated"))
      (unless (find stage lifecycle :test #'string=)
        (error "Learning lifecycle missing stage: ~A" stage)))
    (dolist (status '("open" "closed"))
      (unless (find status statuses :test #'string=)
        (error "Learning allowed status missing: ~A" status)))
    (unless (find "data/private/" prefixes :test #'string=)
      (error "Learning evidence refs must allow private evidence paths"))
    (unless (find "mhj learning status"
                  (coerce (getf policy :commands) 'list)
                  :test #'string=)
      (error "Learning status command must stay in SSOT"))
    (unless (find "mhj learning record <json-payload>"
                  (coerce (getf policy :commands) 'list)
                  :test #'string=)
      (error "Learning record command must stay in SSOT"))
    t))

(defun validate-evidence-graph-policy (policy)
  (let ((private-root (getf policy :private_root))
        (sources (coerce (getf policy :private_sources) 'list))
        (node-kinds (coerce (getf policy :node_kinds) 'list))
        (edge-kinds (coerce (getf policy :edge_kinds) 'list))
        (summary-fields (coerce (getf policy :public_summary_fields) 'list))
        (prefixes (coerce (getf policy :allowed_evidence_prefixes) 'list)))
    (unless (string= (getf policy :context) "AgentCluster")
      (error "Evidence graph policy must belong to AgentCluster"))
    (unless (and (stringp private-root)
                 (string= private-root "data/private"))
      (error "Evidence graph private root must stay data/private"))
    (unless (getf policy :private_graph_required)
      (error "Evidence graph must require private graph evidence"))
    (unless (getf policy :public_status_redacted)
      (error "Evidence graph public status must stay redacted"))
    (when (getf policy :raw_evidence_public_allowed)
      (error "Evidence graph must not expose raw evidence publicly"))
    (dolist (kind '("learning_observation" "evidence_artifact"))
      (unless (find kind node-kinds :test #'string=)
        (error "Evidence graph missing node kind: ~A" kind)))
    (unless (find "supports" edge-kinds :test #'string=)
      (error "Evidence graph must include supports edges"))
    (unless (> (length sources) 0)
      (error "Evidence graph sources are required"))
    (dolist (source sources)
      (let ((key (getf source :key))
            (path (getf source :path))
            (kind (getf source :node_kind))
            (format (getf source :format)))
        (when (or (null key) (string= key ""))
          (error "Evidence graph source key is required"))
        (unless (and (stringp path)
                     (>= (length path) 13)
                     (string= "data/private/" (subseq path 0 13)))
          (error "Evidence graph source ~A must stay under data/private" key))
        (unless (find kind node-kinds :test #'string=)
          (error "Evidence graph source ~A has unknown node kind ~A" key kind))
        (unless (find format '("jsonl" "directory") :test #'string=)
          (error "Evidence graph source ~A has unsupported format ~A" key format))))
    (dolist (field '("node_count" "edge_count" "by_node_kind" "by_edge_kind" "checked_at"))
      (unless (find field summary-fields :test #'string=)
        (error "Evidence graph summary missing field: ~A" field)))
    (unless (find "data/private/" prefixes :test #'string=)
      (error "Evidence graph evidence refs must allow private evidence paths"))
    (unless (find "mhj evidence status"
                  (coerce (getf policy :commands) 'list)
                  :test #'string=)
      (error "Evidence graph status command must stay in SSOT"))
    t))

(defun validate-confidence-policy (policy)
  (let ((levels (coerce (getf policy :levels) 'list))
        (inputs (coerce (getf policy :inputs) 'list))
        (rules (coerce (getf policy :cap_rules) 'list))
        (summary-fields (coerce (getf policy :public_summary_fields) 'list)))
    (unless (string= (getf policy :context) "AgentCluster")
      (error "Confidence policy must belong to AgentCluster"))
    (unless (string= (getf policy :assessor_key) "confidence_assessor")
      (error "Confidence assessor key must stay explicit"))
    (unless (getf policy :confidence_is_cap)
      (error "Confidence must be represented as a cap"))
    (when (getf policy :self_report_allowed)
      (error "Agent confidence self-reporting must stay forbidden"))
    (unless (getf policy :public_status_redacted)
      (error "Confidence status must stay redacted"))
    (when (getf policy :raw_evidence_public_allowed)
      (error "Confidence status must not expose raw evidence"))
    (dolist (level '("blocked" "low" "medium" "high"))
      (unless (find level levels :test #'string=)
        (error "Confidence level missing: ~A" level)))
    (dolist (input '("evidence_graph" "learning_ledger" "quality_gate" "public_safety"))
      (unless (find input inputs :test #'string=)
        (error "Confidence input missing: ~A" input)))
    (unless (> (length rules) 0)
      (error "Confidence cap rules are required"))
    (dolist (rule rules)
      (let ((key (getf rule :key))
            (when-value (getf rule :when))
            (cap (getf rule :cap)))
        (when (or (null key) (string= key ""))
          (error "Confidence rule key is required"))
        (when (or (null when-value) (string= when-value ""))
          (error "Confidence rule ~A must declare a condition" key))
        (unless (find cap levels :test #'string=)
          (error "Confidence rule ~A has invalid cap ~A" key cap))))
    (dolist (field '("level_cap" "self_report_allowed" "evidence_link_count" "public_safety_ok" "checked_at"))
      (unless (find field summary-fields :test #'string=)
        (error "Confidence summary missing field: ~A" field)))
    (unless (find "mhj confidence status"
                  (coerce (getf policy :commands) 'list)
                  :test #'string=)
      (error "Confidence status command must stay in SSOT"))
    t))

(defun validate-ddd-registry ()
  (let ((contexts (make-hash-table :test #'equal))
        (concepts (make-hash-table :test #'equal))
        (aliases (make-hash-table :test #'equal))
        (patterns (make-hash-table :test #'equal))
        (used-patterns (make-hash-table :test #'equal)))
    (dolist (context (coerce *bounded-contexts* 'list))
      (let ((name (getf context :name)))
        (when (or (null name) (string= name ""))
          (error "Bounded context name is required"))
        (when (gethash name contexts)
          (error "Duplicate bounded context: ~A" name))
        (setf (gethash name contexts) t)))
    (dolist (pattern (coerce *ddd-patterns* 'list))
      (unless (find pattern '("Entity" "ValueObject" "Aggregate" "DomainEvent"
                              "Repository" "Policy" "Port" "Adapter"
                              "AntiCorruptionLayer")
                    :test #'string=)
        (error "Unknown DDD pattern: ~A" pattern))
      (setf (gethash pattern patterns) t))
    (dolist (concept (coerce *concept-registry* 'list))
      (let ((name (getf concept :canonical_name))
            (context (getf concept :bounded_context))
            (kind (getf concept :ddd_kind))
            (targets (getf concept :generated_targets)))
        (when (or (null name) (string= name ""))
          (error "Concept canonical_name is required"))
        (when (gethash name concepts)
          (error "Duplicate concept: ~A" name))
        (setf (gethash name concepts) t)
        (unless (gethash context contexts)
          (error "Concept ~A references unknown bounded context ~A" name context))
        (unless (gethash kind patterns)
          (error "Concept ~A references unknown DDD kind ~A" name kind))
        (setf (gethash kind used-patterns) t)
        (unless (> (length targets) 0)
          (error "Concept ~A must declare generated targets" name))
        (dolist (alias (coerce (getf concept :allowed_aliases) 'list))
          (let ((key (string-downcase alias)))
            (when (or (string= key "") (gethash key aliases))
              (error "Duplicate or empty concept alias: ~A" alias))
            (setf (gethash key aliases) name)))))
    (dolist (concept (coerce *concept-registry* 'list))
      (dolist (related (coerce (getf concept :related_concepts) 'list))
        (unless (gethash related concepts)
          (error "Concept ~A references unknown related concept ~A"
                 (getf concept :canonical_name) related))))
    (dolist (pattern (coerce *ddd-patterns* 'list))
      (unless (gethash pattern used-patterns)
        (error "DDD pattern is not used by any concept: ~A" pattern)))
    (unless (> (length *domain-events*) 0)
      (error "Domain events must be defined in SSOT"))
    (dolist (event (coerce *domain-events* 'list))
      (let ((name (getf event :name))
            (context (getf event :bounded_context))
            (emitted-by (getf event :emitted_by))
            (payload-fields (getf event :payload_fields)))
        (when (or (null name) (string= name ""))
          (error "Domain event name is required"))
        (unless (gethash context contexts)
          (error "Domain event ~A references unknown bounded context ~A" name context))
        (unless (gethash emitted-by concepts)
          (error "Domain event ~A references unknown emitter concept ~A" name emitted-by))
        (unless (> (length payload-fields) 0)
          (error "Domain event ~A must declare payload fields" name))))
    (unless (> (length *harness-case-contracts*) 0)
      (error "Harness case contracts must be defined in SSOT"))
    (dolist (harness (coerce *harness-case-contracts* 'list))
      (let ((name (getf harness :name))
            (context (getf harness :bounded_context))
            (command (getf harness :command))
            (target (getf harness :evidence_target)))
        (when (or (null name) (string= name ""))
          (error "Harness case name is required"))
        (unless (gethash context contexts)
          (error "Harness case ~A references unknown bounded context ~A" name context))
        (when (or (null command) (string= command ""))
          (error "Harness case ~A must declare a command" name))
        (when (or (null target) (string= target ""))
          (error "Harness case ~A must declare an evidence target" name))))
    t))

(defun validate-control-plane-policy (policy)
  (let ((ledger (getf policy :private_manifest_ledger))
        (decision-kinds (coerce (getf policy :allowed_decision_kinds) 'list))
        (authority-profiles (coerce (getf policy :allowed_authority_profiles) 'list))
        (lease-statuses (coerce (getf policy :allowed_lease_statuses) 'list))
        (required-fields (coerce (getf policy :required_fields) 'list))
        (summary-fields (coerce (getf policy :public_summary_fields) 'list))
        (min-lease (getf policy :min_lease_seconds))
        (max-lease (getf policy :max_lease_seconds)))
    (unless (string= (getf policy :context) "AgentOps")
      (error "Control-plane policy must belong to AgentOps"))
    (unless (and (stringp ledger)
                 (>= (length ledger) 13)
                 (string= "data/private/" (subseq ledger 0 13))
                 (>= (length ledger) 6)
                 (string= ".jsonl" (subseq ledger (- (length ledger) 6))))
      (error "Control-plane manifest ledger must stay under data/private as JSONL"))
    (unless (and (getf policy :manifest_required)
                 (getf policy :append_only)
                 (getf policy :public_status_redacted))
      (error "Control-plane manifests must be append-only, required, and redacted"))
    (when (getf policy :raw_rationale_public_allowed)
      (error "Control-plane status must not expose raw rationale"))
    (unless (getf policy :verifier_separation_required)
      (error "Control-plane verifier separation must be required"))
    (unless (and (integerp min-lease) (integerp max-lease) (< min-lease max-lease))
      (error "Control-plane lease bounds must be valid"))
    (dolist (kind '("loop_once" "loop_worker_cycle" "checkpoint_write"))
      (unless (find kind decision-kinds :test #'string=)
        (error "Control-plane decision kind missing: ~A" kind)))
    (dolist (profile '("local_readonly" "external_write_gated"))
      (unless (find profile authority-profiles :test #'string=)
        (error "Control-plane authority profile missing: ~A" profile)))
    (dolist (status '("issued" "active" "finished" "aborted" "quarantined"))
      (unless (find status lease-statuses :test #'string=)
        (error "Control-plane lease status missing: ~A" status)))
    (dolist (field '("decision_kind"
                     "policy_version"
                     "ontology_version"
                     "authority_profile"
                     "selected_route"
                     "reviewer_role"
                     "verifier_role"
                     "lease_seconds"
                     "lease_status"
                     "evidence_refs"
                     "output_ref"))
      (unless (find field required-fields :test #'string=)
        (error "Control-plane manifest missing required field: ~A" field)))
    (dolist (field '("count"
                     "invalid_manifest_count"
                     "manifest_debt_count"
                     "verifier_violation_count"
                     "by_decision_kind"
                     "by_authority_profile"
                     "by_lease_status"
                     "checked_at"))
      (unless (find field summary-fields :test #'string=)
        (error "Control-plane summary missing field: ~A" field)))
    (unless (find "mhj control-plane status"
                  (coerce (getf policy :commands) 'list)
                  :test #'string=)
      (error "Control-plane status command must stay in SSOT"))
    t))

(defun validate-translation-policy (policy)
  (let ((ledger (getf policy :private_loss_ledger))
        (manifest-root (getf policy :private_manifest_root))
        (contexts (coerce (getf policy :allowed_contexts) 'list))
        (required-fields (coerce (getf policy :required_manifest_fields) 'list))
        (levels (coerce (getf policy :loss_levels) 'list))
        (categories (coerce (getf policy :allowed_loss_categories) 'list))
        (forbidden-categories (coerce (getf policy :forbidden_loss_categories) 'list))
        (summary-fields (coerce (getf policy :public_summary_fields) 'list)))
    (unless (string= (getf policy :context) "AgentCluster")
      (error "Translation policy must belong to AgentCluster"))
    (unless (and (stringp ledger)
                 (>= (length ledger) 13)
                 (string= "data/private/" (subseq ledger 0 13)))
      (error "Translation loss ledger must stay under data/private"))
    (unless (and (stringp manifest-root)
                 (>= (length manifest-root) 13)
                 (string= "data/private/" (subseq manifest-root 0 13)))
      (error "Translation manifest root must stay under data/private"))
    (unless (getf policy :manifest_required)
      (error "Translation manifests must be required for context moves"))
    (unless (getf policy :public_status_redacted)
      (error "Translation public status must stay redacted"))
    (when (getf policy :raw_loss_public_allowed)
      (error "Translation status must not expose raw semantic losses"))
    (dolist (context '("AgentCluster" "KnowledgeIndex" "AgentOps" "SecurityPolicy"))
      (unless (find context contexts :test #'string=)
        (error "Translation policy missing context: ~A" context)))
    (dolist (field '("source_context"
                     "target_context"
                     "source_version"
                     "target_version"
                     "preserved_rules"
                     "known_losses"
                     "owner"
                     "evidence_refs"))
      (unless (find field required-fields :test #'string=)
        (error "Translation manifest missing required field: ~A" field)))
    (dolist (level '("l0_none" "l1_note" "l2_degraded" "l3_review_required" "l4_forbidden"))
      (unless (find level levels :test #'string=)
        (error "Translation loss level missing: ~A" level)))
    (dolist (category '("mapping_gap" "authority" "security_boundary" "financial_commitment"))
      (unless (find category categories :test #'string=)
        (error "Translation loss category missing: ~A" category)))
    (dolist (category '("authority" "security_boundary" "user_consent" "deletion_semantics" "audit_record" "legal_obligation" "financial_commitment"))
      (unless (find category forbidden-categories :test #'string=)
        (error "Translation forbidden loss category missing: ~A" category)))
    (dolist (field '("open_debt_count" "forbidden_loss_count" "invalid_manifest_count" "missing_manifest_count" "checked_at"))
      (unless (find field summary-fields :test #'string=)
        (error "Translation summary missing field: ~A" field)))
    (unless (find "mhj translation status"
                  (coerce (getf policy :commands) 'list)
                  :test #'string=)
      (error "Translation status command must stay in SSOT"))
    t))

(defun write-generated-artifacts (root)
  (validate-ssot)
  (write-json-file (merge-pathnames "generated/commands.generated.json" root)
                   (list :project *project*
                         :commands (coerce *commands* 'vector)))
  (write-json-file (merge-pathnames "generated/concepts.generated.json" root)
                   (list :bounded_contexts *bounded-contexts*
                         :ddd_patterns *ddd-patterns*
                         :concepts *concept-registry*
                         :domain_events *domain-events*
                         :harness_case_contracts *harness-case-contracts*
                         :generated_artifact_contracts *generated-artifact-contracts*
                         :planning_rules *planning-rules*
                         :knowledge_index_schema *knowledge-index-schema*))
  (write-json-file (merge-pathnames "generated/finance.generated.json" root)
                   (list :entities *finance-entities*
                         :transaction_ir *transaction-ir*))
  (write-json-file (merge-pathnames "generated/commerce.generated.json" root)
                   (list :entities *commerce-entities*
                         :purchase_ir *purchase-ir*))
  (write-json-file (merge-pathnames "generated/storage.generated.json" root)
                   *storage-policy*)
  (write-json-file (merge-pathnames "generated/household.generated.json" root)
                   *household-policy*)
  (write-json-file (merge-pathnames "generated/recommendations.generated.json" root)
                   *recommendation-policy*)
  (write-json-file (merge-pathnames "generated/scheduler.generated.json" root)
                   *scheduler-policy*)
  (write-json-file (merge-pathnames "generated/security.generated.json" root)
                   *security-policy*)
  (write-json-file (merge-pathnames "generated/connectors.generated.json" root)
                   *connector-policy*)
  (write-json-file (merge-pathnames "generated/agent_cluster.generated.json" root)
                   *agent-cluster-policy*)
  (write-json-file (merge-pathnames "generated/learning.generated.json" root)
                   *learning-policy*)
  (write-json-file (merge-pathnames "generated/evidence.generated.json" root)
                   *evidence-graph-policy*)
  (write-json-file (merge-pathnames "generated/confidence.generated.json" root)
                   *confidence-policy*)
  (write-json-file (merge-pathnames "generated/translation.generated.json" root)
                   *translation-policy*)
  (write-json-file (merge-pathnames "generated/control_plane.generated.json" root)
                   *control-plane-policy*)
  (write-json-file (merge-pathnames "generated/linear.generated.json" root)
                   *linear-policy*)
  (write-json-file (merge-pathnames "generated/planner.generated.json" root)
                   *planner-policy*)
  t)

(defun write-json-file (path value)
  (ensure-directories-exist path)
  (with-open-file (stream path
                          :direction :output
                          :if-exists :supersede
                          :if-does-not-exist :create)
    (write-json-value value stream)
    (terpri stream)))

(defun write-json-value (value stream)
  (cond
    ((stringp value) (write-json-string value stream))
    ((integerp value) (princ value stream))
    ((eq value t) (princ "true" stream))
    ((null value) (princ "false" stream))
    ((vectorp value) (write-json-array value stream))
    ((plist-object-p value) (write-json-object value stream))
    ((listp value) (write-json-array (coerce value 'vector) stream))
    (t (write-json-string (princ-to-string value) stream))))

(defun write-json-object (plist stream)
  (princ "{" stream)
  (loop for (key value) on plist by #'cddr
        for first = t then nil
        do (progn
             (unless first (princ "," stream))
             (write-json-string (json-key key) stream)
             (princ ":" stream)
             (write-json-value value stream)))
  (princ "}" stream))

(defun write-json-array (vector stream)
  (princ "[" stream)
  (loop for index from 0 below (length vector)
        do (progn
             (unless (= index 0) (princ "," stream))
             (write-json-value (aref vector index) stream)))
  (princ "]" stream))

(defun write-json-string (value stream)
  (princ "\"" stream)
  (loop for char across value
        do (case char
             (#\" (princ "\\\"" stream))
             (#\\ (princ "\\\\" stream))
             (#\Newline (princ "\\n" stream))
             (#\Return (princ "\\r" stream))
             (#\Tab (princ "\\t" stream))
             (otherwise (princ char stream))))
  (princ "\"" stream))

(defun plist-object-p (value)
  (and (listp value)
       (evenp (length value))
       (loop for tail on value by #'cddr
             always (keywordp (first tail)))))

(defun json-key (key)
  (string-downcase (symbol-name key)))
