(in-package #:myhome-jarvis.ssot)

(defun validate-ddd-registry ()
  (let ((contexts (make-hash-table :test #'equal))
        (concepts (make-hash-table :test #'equal))
        (aliases (make-hash-table :test #'equal))
        (patterns (make-hash-table :test #'equal))
        (used-patterns (make-hash-table :test #'equal)))
    (collect-ddd-contexts contexts)
    (collect-ddd-patterns patterns)
    (validate-ddd-concepts contexts concepts aliases patterns used-patterns)
    (validate-ddd-related-concepts concepts)
    (validate-ddd-used-patterns used-patterns)
    (validate-domain-events contexts concepts)
    (validate-harness-contracts contexts)
    t))

(defun collect-ddd-contexts (contexts)
  (dolist (context (coerce *bounded-contexts* 'list))
    (let ((name (getf context :name)))
      (require-string-value name "Bounded context name is required")
      (require-false (gethash name contexts) "Duplicate bounded context: ~A" name)
      (setf (gethash name contexts) t))))

(defun collect-ddd-patterns (patterns)
  (dolist (pattern (coerce *ddd-patterns* 'list))
    (require-member pattern '("Entity" "ValueObject" "Aggregate"
                              "DomainEvent" "Repository" "Policy" "Port"
                              "Adapter" "AntiCorruptionLayer")
                    "Unknown DDD pattern: ~A" pattern)
    (setf (gethash pattern patterns) t)))

(defun validate-ddd-concepts (contexts concepts aliases patterns used-patterns)
  (dolist (concept (coerce *concept-registry* 'list))
    (let ((name (getf concept :canonical_name))
          (context (getf concept :bounded_context))
          (kind (getf concept :ddd_kind))
          (targets (getf concept :generated_targets)))
      (require-string-value name "Concept canonical_name is required")
      (require-false (gethash name concepts) "Duplicate concept: ~A" name)
      (setf (gethash name concepts) t)
      (require-true (gethash context contexts)
                    "Concept ~A references unknown bounded context ~A"
                    name context)
      (require-true (gethash kind patterns)
                    "Concept ~A references unknown DDD kind ~A" name kind)
      (setf (gethash kind used-patterns) t)
      (require-true (> (length targets) 0)
                    "Concept ~A must declare generated targets" name)
      (validate-ddd-aliases concept aliases name))))

(defun validate-ddd-aliases (concept aliases name)
  (dolist (alias (coerce (getf concept :allowed_aliases) 'list))
    (let ((key (string-downcase alias)))
      (require-false (or (string= key "") (gethash key aliases))
                     "Duplicate or empty concept alias: ~A" alias)
      (setf (gethash key aliases) name))))
