(in-package #:myhome-jarvis.ssot)

(defparameter *generated-artifact-contracts*
  #((:name "concepts" :path "generated/concepts.generated.json" :owner "KnowledgeIndex")
    (:name "commands" :path "generated/commands.generated.json" :owner "HomeControl")
    (:name "finance" :path "generated/finance.generated.json" :owner "HouseholdFinance")
    (:name "commerce" :path "generated/commerce.generated.json" :owner "CommerceIntelligence")
    (:name "connectors" :path "generated/connectors.generated.json" :owner "ConnectorReadiness")
    (:name "agent_cluster" :path "generated/agent_cluster.generated.json" :owner "AgentCluster")
    (:name "learning" :path "generated/learning.generated.json" :owner "AgentCluster")
    (:name "evidence" :path "generated/evidence.generated.json" :owner "AgentCluster")
    (:name "confidence" :path "generated/confidence.generated.json" :owner "AgentCluster")
    (:name "translation" :path "generated/translation.generated.json" :owner "AgentCluster")
    (:name "control_plane" :path "generated/control_plane.generated.json" :owner "AgentOps")
    (:name "incidents" :path "generated/incidents.generated.json" :owner "AgentCluster")
    (:name "evidence_quality" :path "generated/evidence_quality.generated.json" :owner "AgentCluster")
	    (:name "review" :path "generated/review.generated.json" :owner "AgentCluster")
	    (:name "assistant_vision" :path "generated/assistant_vision.generated.json" :owner "AgentOps")
	    (:name "codex_cost" :path "generated/codex_cost.generated.json" :owner "AgentOps")
	    (:name "authority" :path "generated/authority.generated.json" :owner "AgentCluster")
    (:name "code_shape" :path "generated/code_shape.generated.json" :owner "AgentCluster")
    (:name "storage" :path "generated/storage.generated.json" :owner "StorageLake")
    (:name "household" :path "generated/household.generated.json" :owner "HouseholdFinance")
    (:name "recommendations" :path "generated/recommendations.generated.json" :owner "CommerceIntelligence")
    (:name "scheduler" :path "generated/scheduler.generated.json" :owner "AgentOps")
    (:name "security" :path "generated/security.generated.json" :owner "SecurityPolicy")
    (:name "linear" :path "generated/linear.generated.json" :owner "AgentOps")
    (:name "planner" :path "generated/planner.generated.json" :owner "AgentOps")))
