(in-package #:myhome-jarvis.ssot)
(defparameter *verification-units*
  #((:id "public-safety" :name "Public safety" :kind "release-check"
     :timeout 10 :setup "go" :history t
     :commands #("go run ./cmd/mhj security check"
                 "go run ./cmd/mhj security history"))
    (:id "ssot" :name "SSOT and generated artifacts" :kind "conformance"
     :timeout 10 :setup "lisp" :cache "ssot"
	     :hash_inputs #(".github/workflows/quality.yml" "lisp/ssot/**" "lisp/scripts/**"
	                    "generated/**")
     :commands #("ros -Q run -- --script lisp/scripts/validate-ssot.lisp"
                 "ros -Q run -- --script lisp/scripts/codegen.lisp"
                 "test -s generated/verification_graph.generated.json"
                 "test -s generated/github_quality_workflow.generated.yml"
                 "test -s generated/gitlab_quality.generated.yml"
                 "test -s generated/local_quality.generated.mk"
                 "test -s generated/bazel_quality.generated.bzl"
                 "test -s generated/control_plane_verification.generated.json"
                 "test -s generated/verification_evidence.generated.json"
                 "test -s generated/pdca.generated.json"
                 "test -s generated/verification_graph.schema.generated.json"
                 "test -s generated/verification_conformance.generated.json"
                 "test -s generated/verification_tests.generated.json"
                 "test -s generated/release_pipeline.generated.json"
                 "test -s generated/codex_cost.generated.json"
                 "git diff --exit-code -- generated .github/workflows/quality.yml docs/verification-graph.md"))
    (:id "go" :name "Go daemon and CLI" :kind "unit-test"
     :timeout 10 :setup "go" :cache "go"
     :hash_inputs #(".github/workflows/quality.yml" ".go-version"
                    "rust-toolchain.toml" "go.mod" "go.sum" "cmd/**/*.go"
                    "internal/**/*.go" "generated/*.json"
                    "generated/github_quality_workflow.generated.yml")
     :commands #("go run ./cmd/mhj ci verify"
                 "go run ./cmd/mhj verification verify"
                 "go run ./cmd/mhj verification evidence"
                 "go run ./cmd/mhj pdca status"
                 "go run ./cmd/mhj control-plane verify"
                 "go run ./cmd/mhj toolchain verify"
                 "go run ./cmd/mhj code-shape status"
                 "go run ./cmd/mhj harness home"
                 "go run ./cmd/mhj harness finance"
                 "go run ./cmd/mhj harness commerce"
                 "go test ./..."
                 "go vet ./..."
                 "unformatted=\"$(gofmt -l cmd internal)\""
                 "if [ -n \"$unformatted\" ]; then"
                 "  echo \"$unformatted\""
                 "  exit 1"
                 "fi"))
    (:id "rust" :name "Rust core and harness" :kind "integration-test"
     :timeout 10 :setup "rust" :cache "rust"
     :hash_inputs #(".github/workflows/quality.yml" "rust-toolchain.toml"
                    "Cargo.toml" "Cargo.lock" "crates/**" "fixtures/**")
     :commands #("cargo test --workspace"
                 "cargo test -p mhj-core benchmark_smoke -- --nocapture"
                 "cargo fmt --check"
                 "cargo clippy --workspace -- -D warnings"))
    (:id "flutter" :name "Flutter local client" :kind "lint"
     :timeout 10 :setup "flutter" :cache "flutter" :working_directory "apps/flutter"
     :hash_inputs #(".github/workflows/quality.yml" "apps/flutter/**"
                    "generated/commands.generated.json"
                    "generated/connectors.generated.json"
                    "generated/agent_cluster.generated.json"
                    "generated/learning.generated.json"
                    "generated/evidence.generated.json"
                    "generated/confidence.generated.json"
                    "generated/translation.generated.json"
                    "generated/control_plane.generated.json"
                    "generated/incidents.generated.json"
                    "generated/evidence_quality.generated.json"
                    "generated/review.generated.json"
                    "generated/pdca.generated.json"
                    "generated/code_shape.generated.json"
                    "generated/authority.generated.json")
     :commands #("flutter test" "flutter analyze"))))
